// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// JobsClient is an autogenerated mock type for the JobsClient type
type JobsClient struct {
	mock.Mock
}

// ClaimJob provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) ClaimJob(ctx context.Context, in *gen.ClaimJobRequest, opts ...grpc.CallOption) (*gen.ClaimJobResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ClaimJob")
	}

	var r0 *gen.ClaimJobResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ClaimJobRequest, ...grpc.CallOption) (*gen.ClaimJobResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ClaimJobRequest, ...grpc.CallOption) *gen.ClaimJobResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClaimJobResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.ClaimJobRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobByID provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) GetJobByID(ctx context.Context, in *gen.GetJobByIDRequest, opts ...grpc.CallOption) (*gen.Job, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetJobByID")
	}

	var r0 *gen.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetJobByIDRequest, ...grpc.CallOption) (*gen.Job, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetJobByIDRequest, ...grpc.CallOption) *gen.Job); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetJobByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobLogs provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) GetJobLogs(ctx context.Context, in *gen.GetJobLogsRequest, opts ...grpc.CallOption) (*gen.GetJobLogsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetJobLogs")
	}

	var r0 *gen.GetJobLogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetJobLogsRequest, ...grpc.CallOption) (*gen.GetJobLogsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetJobLogsRequest, ...grpc.CallOption) *gen.GetJobLogsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetJobLogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetJobLogsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestJobForApply provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) GetLatestJobForApply(ctx context.Context, in *gen.GetLatestJobForApplyRequest, opts ...grpc.CallOption) (*gen.Job, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestJobForApply")
	}

	var r0 *gen.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetLatestJobForApplyRequest, ...grpc.CallOption) (*gen.Job, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetLatestJobForApplyRequest, ...grpc.CallOption) *gen.Job); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetLatestJobForApplyRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestJobForPlan provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) GetLatestJobForPlan(ctx context.Context, in *gen.GetLatestJobForPlanRequest, opts ...grpc.CallOption) (*gen.Job, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestJobForPlan")
	}

	var r0 *gen.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetLatestJobForPlanRequest, ...grpc.CallOption) (*gen.Job, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetLatestJobForPlanRequest, ...grpc.CallOption) *gen.Job); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetLatestJobForPlanRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveJobLogs provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) SaveJobLogs(ctx context.Context, in *gen.SaveJobLogsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SaveJobLogs")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SaveJobLogsRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SaveJobLogsRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SaveJobLogsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetJobStatus provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) SetJobStatus(ctx context.Context, in *gen.SetJobStatusInput, opts ...grpc.CallOption) (*gen.Job, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetJobStatus")
	}

	var r0 *gen.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SetJobStatusInput, ...grpc.CallOption) (*gen.Job, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SetJobStatusInput, ...grpc.CallOption) *gen.Job); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SetJobStatusInput, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToJobCancellationEvent provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) SubscribeToJobCancellationEvent(ctx context.Context, in *gen.SubscribeToJobCancellationEventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[gen.JobCancellationEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToJobCancellationEvent")
	}

	var r0 grpc.ServerStreamingClient[gen.JobCancellationEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToJobCancellationEventRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[gen.JobCancellationEvent], error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToJobCancellationEventRequest, ...grpc.CallOption) grpc.ServerStreamingClient[gen.JobCancellationEvent]); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[gen.JobCancellationEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SubscribeToJobCancellationEventRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToJobEvents provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) SubscribeToJobEvents(ctx context.Context, in *gen.SubscribeToJobEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[gen.JobEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToJobEvents")
	}

	var r0 grpc.ServerStreamingClient[gen.JobEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToJobEventsRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[gen.JobEvent], error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToJobEventsRequest, ...grpc.CallOption) grpc.ServerStreamingClient[gen.JobEvent]); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[gen.JobEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SubscribeToJobEventsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToJobLogStream provides a mock function with given fields: ctx, in, opts
func (_m *JobsClient) SubscribeToJobLogStream(ctx context.Context, in *gen.SubscribeToJobLogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[gen.JobLogStreamEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToJobLogStream")
	}

	var r0 grpc.ServerStreamingClient[gen.JobLogStreamEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToJobLogStreamRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[gen.JobLogStreamEvent], error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToJobLogStreamRequest, ...grpc.CallOption) grpc.ServerStreamingClient[gen.JobLogStreamEvent]); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[gen.JobLogStreamEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SubscribeToJobLogStreamRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobsClient creates a new instance of JobsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobsClient {
	mock := &JobsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
