// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// RunsClient is an autogenerated mock type for the RunsClient type
type RunsClient struct {
	mock.Mock
}

// ApplyRun provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) ApplyRun(ctx context.Context, in *gen.ApplyRunRequest, opts ...grpc.CallOption) (*gen.Run, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ApplyRun")
	}

	var r0 *gen.Run
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ApplyRunRequest, ...grpc.CallOption) (*gen.Run, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ApplyRunRequest, ...grpc.CallOption) *gen.Run); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.ApplyRunRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelRun provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) CancelRun(ctx context.Context, in *gen.CancelRunRequest, opts ...grpc.CallOption) (*gen.Run, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CancelRun")
	}

	var r0 *gen.Run
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CancelRunRequest, ...grpc.CallOption) (*gen.Run, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CancelRunRequest, ...grpc.CallOption) *gen.Run); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CancelRunRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRun provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) CreateRun(ctx context.Context, in *gen.CreateRunRequest, opts ...grpc.CallOption) (*gen.Run, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateRun")
	}

	var r0 *gen.Run
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateRunRequest, ...grpc.CallOption) (*gen.Run, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateRunRequest, ...grpc.CallOption) *gen.Run); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateRunRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplyByID provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) GetApplyByID(ctx context.Context, in *gen.GetApplyByIDRequest, opts ...grpc.CallOption) (*gen.Apply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApplyByID")
	}

	var r0 *gen.Apply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetApplyByIDRequest, ...grpc.CallOption) (*gen.Apply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetApplyByIDRequest, ...grpc.CallOption) *gen.Apply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Apply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetApplyByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlanByID provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) GetPlanByID(ctx context.Context, in *gen.GetPlanByIDRequest, opts ...grpc.CallOption) (*gen.Plan, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanByID")
	}

	var r0 *gen.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetPlanByIDRequest, ...grpc.CallOption) (*gen.Plan, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetPlanByIDRequest, ...grpc.CallOption) *gen.Plan); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetPlanByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunByID provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) GetRunByID(ctx context.Context, in *gen.GetRunByIDRequest, opts ...grpc.CallOption) (*gen.Run, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRunByID")
	}

	var r0 *gen.Run
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetRunByIDRequest, ...grpc.CallOption) (*gen.Run, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetRunByIDRequest, ...grpc.CallOption) *gen.Run); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetRunByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRunVariables provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) GetRunVariables(ctx context.Context, in *gen.GetRunVariablesRequest, opts ...grpc.CallOption) (*gen.GetRunVariablesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRunVariables")
	}

	var r0 *gen.GetRunVariablesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetRunVariablesRequest, ...grpc.CallOption) (*gen.GetRunVariablesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetRunVariablesRequest, ...grpc.CallOption) *gen.GetRunVariablesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetRunVariablesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetRunVariablesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRuns provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) GetRuns(ctx context.Context, in *gen.GetRunsRequest, opts ...grpc.CallOption) (*gen.GetRunsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRuns")
	}

	var r0 *gen.GetRunsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetRunsRequest, ...grpc.CallOption) (*gen.GetRunsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetRunsRequest, ...grpc.CallOption) *gen.GetRunsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetRunsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetRunsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToRunEvents provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) SubscribeToRunEvents(ctx context.Context, in *gen.SubscribeToRunEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[gen.RunEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToRunEvents")
	}

	var r0 grpc.ServerStreamingClient[gen.RunEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToRunEventsRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[gen.RunEvent], error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToRunEventsRequest, ...grpc.CallOption) grpc.ServerStreamingClient[gen.RunEvent]); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[gen.RunEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SubscribeToRunEventsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateApply provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) UpdateApply(ctx context.Context, in *gen.UpdateApplyRequest, opts ...grpc.CallOption) (*gen.Apply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApply")
	}

	var r0 *gen.Apply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateApplyRequest, ...grpc.CallOption) (*gen.Apply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateApplyRequest, ...grpc.CallOption) *gen.Apply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Apply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateApplyRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePlan provides a mock function with given fields: ctx, in, opts
func (_m *RunsClient) UpdatePlan(ctx context.Context, in *gen.UpdatePlanRequest, opts ...grpc.CallOption) (*gen.Plan, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlan")
	}

	var r0 *gen.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdatePlanRequest, ...grpc.CallOption) (*gen.Plan, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdatePlanRequest, ...grpc.CallOption) *gen.Plan); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdatePlanRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRunsClient creates a new instance of RunsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RunsClient {
	mock := &RunsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
