// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// TerraformModulesClient is an autogenerated mock type for the TerraformModulesClient type
type TerraformModulesClient struct {
	mock.Mock
}

// CreateTerraformModule provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) CreateTerraformModule(ctx context.Context, in *gen.CreateTerraformModuleRequest, opts ...grpc.CallOption) (*gen.TerraformModule, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTerraformModule")
	}

	var r0 *gen.TerraformModule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformModuleRequest, ...grpc.CallOption) (*gen.TerraformModule, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformModuleRequest, ...grpc.CallOption) *gen.TerraformModule); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateTerraformModuleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTerraformModuleAttestation provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) CreateTerraformModuleAttestation(ctx context.Context, in *gen.CreateTerraformModuleAttestationRequest, opts ...grpc.CallOption) (*gen.TerraformModuleAttestation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTerraformModuleAttestation")
	}

	var r0 *gen.TerraformModuleAttestation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformModuleAttestationRequest, ...grpc.CallOption) (*gen.TerraformModuleAttestation, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformModuleAttestationRequest, ...grpc.CallOption) *gen.TerraformModuleAttestation); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModuleAttestation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateTerraformModuleAttestationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTerraformModuleVersion provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) CreateTerraformModuleVersion(ctx context.Context, in *gen.CreateTerraformModuleVersionRequest, opts ...grpc.CallOption) (*gen.TerraformModuleVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTerraformModuleVersion")
	}

	var r0 *gen.TerraformModuleVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformModuleVersionRequest, ...grpc.CallOption) (*gen.TerraformModuleVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformModuleVersionRequest, ...grpc.CallOption) *gen.TerraformModuleVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModuleVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateTerraformModuleVersionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTerraformModule provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) DeleteTerraformModule(ctx context.Context, in *gen.DeleteTerraformModuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTerraformModule")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformModuleRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformModuleRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteTerraformModuleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTerraformModuleAttestation provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) DeleteTerraformModuleAttestation(ctx context.Context, in *gen.DeleteTerraformModuleAttestationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTerraformModuleAttestation")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformModuleAttestationRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformModuleAttestationRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteTerraformModuleAttestationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTerraformModuleVersion provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) DeleteTerraformModuleVersion(ctx context.Context, in *gen.DeleteTerraformModuleVersionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTerraformModuleVersion")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformModuleVersionRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformModuleVersionRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteTerraformModuleVersionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformModuleAttestationByID provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) GetTerraformModuleAttestationByID(ctx context.Context, in *gen.GetTerraformModuleAttestationByIDRequest, opts ...grpc.CallOption) (*gen.TerraformModuleAttestation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModuleAttestationByID")
	}

	var r0 *gen.TerraformModuleAttestation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleAttestationByIDRequest, ...grpc.CallOption) (*gen.TerraformModuleAttestation, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleAttestationByIDRequest, ...grpc.CallOption) *gen.TerraformModuleAttestation); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModuleAttestation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModuleAttestationByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformModuleAttestations provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) GetTerraformModuleAttestations(ctx context.Context, in *gen.GetTerraformModuleAttestationsRequest, opts ...grpc.CallOption) (*gen.GetTerraformModuleAttestationsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModuleAttestations")
	}

	var r0 *gen.GetTerraformModuleAttestationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleAttestationsRequest, ...grpc.CallOption) (*gen.GetTerraformModuleAttestationsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleAttestationsRequest, ...grpc.CallOption) *gen.GetTerraformModuleAttestationsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetTerraformModuleAttestationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModuleAttestationsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformModuleByID provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) GetTerraformModuleByID(ctx context.Context, in *gen.GetTerraformModuleByIDRequest, opts ...grpc.CallOption) (*gen.TerraformModule, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModuleByID")
	}

	var r0 *gen.TerraformModule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleByIDRequest, ...grpc.CallOption) (*gen.TerraformModule, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleByIDRequest, ...grpc.CallOption) *gen.TerraformModule); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModuleByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformModuleVersionByID provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) GetTerraformModuleVersionByID(ctx context.Context, in *gen.GetTerraformModuleVersionByIDRequest, opts ...grpc.CallOption) (*gen.TerraformModuleVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModuleVersionByID")
	}

	var r0 *gen.TerraformModuleVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleVersionByIDRequest, ...grpc.CallOption) (*gen.TerraformModuleVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleVersionByIDRequest, ...grpc.CallOption) *gen.TerraformModuleVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModuleVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModuleVersionByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformModuleVersions provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) GetTerraformModuleVersions(ctx context.Context, in *gen.GetTerraformModuleVersionsRequest, opts ...grpc.CallOption) (*gen.GetTerraformModuleVersionsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModuleVersions")
	}

	var r0 *gen.GetTerraformModuleVersionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleVersionsRequest, ...grpc.CallOption) (*gen.GetTerraformModuleVersionsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModuleVersionsRequest, ...grpc.CallOption) *gen.GetTerraformModuleVersionsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetTerraformModuleVersionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModuleVersionsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformModules provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) GetTerraformModules(ctx context.Context, in *gen.GetTerraformModulesRequest, opts ...grpc.CallOption) (*gen.GetTerraformModulesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformModules")
	}

	var r0 *gen.GetTerraformModulesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModulesRequest, ...grpc.CallOption) (*gen.GetTerraformModulesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformModulesRequest, ...grpc.CallOption) *gen.GetTerraformModulesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetTerraformModulesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformModulesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTerraformModule provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) UpdateTerraformModule(ctx context.Context, in *gen.UpdateTerraformModuleRequest, opts ...grpc.CallOption) (*gen.TerraformModule, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTerraformModule")
	}

	var r0 *gen.TerraformModule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateTerraformModuleRequest, ...grpc.CallOption) (*gen.TerraformModule, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateTerraformModuleRequest, ...grpc.CallOption) *gen.TerraformModule); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateTerraformModuleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTerraformModuleAttestation provides a mock function with given fields: ctx, in, opts
func (_m *TerraformModulesClient) UpdateTerraformModuleAttestation(ctx context.Context, in *gen.UpdateTerraformModuleAttestationRequest, opts ...grpc.CallOption) (*gen.TerraformModuleAttestation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTerraformModuleAttestation")
	}

	var r0 *gen.TerraformModuleAttestation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateTerraformModuleAttestationRequest, ...grpc.CallOption) (*gen.TerraformModuleAttestation, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateTerraformModuleAttestationRequest, ...grpc.CallOption) *gen.TerraformModuleAttestation); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformModuleAttestation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateTerraformModuleAttestationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTerraformModulesClient creates a new instance of TerraformModulesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerraformModulesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerraformModulesClient {
	mock := &TerraformModulesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
