// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ManagedIdentitiesClient is an autogenerated mock type for the ManagedIdentitiesClient type
type ManagedIdentitiesClient struct {
	mock.Mock
}

// AssignManagedIdentityToWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) AssignManagedIdentityToWorkspace(ctx context.Context, in *gen.AssignManagedIdentityToWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AssignManagedIdentityToWorkspace")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.AssignManagedIdentityToWorkspaceRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.AssignManagedIdentityToWorkspaceRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.AssignManagedIdentityToWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateManagedIdentity provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) CreateManagedIdentity(ctx context.Context, in *gen.CreateManagedIdentityRequest, opts ...grpc.CallOption) (*gen.ManagedIdentity, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateManagedIdentity")
	}

	var r0 *gen.ManagedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityRequest, ...grpc.CallOption) (*gen.ManagedIdentity, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityRequest, ...grpc.CallOption) *gen.ManagedIdentity); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateManagedIdentityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateManagedIdentityAccessRule provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) CreateManagedIdentityAccessRule(ctx context.Context, in *gen.CreateManagedIdentityAccessRuleRequest, opts ...grpc.CallOption) (*gen.ManagedIdentityAccessRule, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateManagedIdentityAccessRule")
	}

	var r0 *gen.ManagedIdentityAccessRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityAccessRuleRequest, ...grpc.CallOption) (*gen.ManagedIdentityAccessRule, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityAccessRuleRequest, ...grpc.CallOption) *gen.ManagedIdentityAccessRule); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentityAccessRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateManagedIdentityAccessRuleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateManagedIdentityAlias provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) CreateManagedIdentityAlias(ctx context.Context, in *gen.CreateManagedIdentityAliasRequest, opts ...grpc.CallOption) (*gen.ManagedIdentity, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateManagedIdentityAlias")
	}

	var r0 *gen.ManagedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityAliasRequest, ...grpc.CallOption) (*gen.ManagedIdentity, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityAliasRequest, ...grpc.CallOption) *gen.ManagedIdentity); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateManagedIdentityAliasRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateManagedIdentityCredentials provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) CreateManagedIdentityCredentials(ctx context.Context, in *gen.CreateManagedIdentityCredentialsRequest, opts ...grpc.CallOption) (*gen.CreateManagedIdentityCredentialsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateManagedIdentityCredentials")
	}

	var r0 *gen.CreateManagedIdentityCredentialsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityCredentialsRequest, ...grpc.CallOption) (*gen.CreateManagedIdentityCredentialsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateManagedIdentityCredentialsRequest, ...grpc.CallOption) *gen.CreateManagedIdentityCredentialsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.CreateManagedIdentityCredentialsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateManagedIdentityCredentialsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteManagedIdentity provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) DeleteManagedIdentity(ctx context.Context, in *gen.DeleteManagedIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManagedIdentity")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteManagedIdentityRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteManagedIdentityRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteManagedIdentityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteManagedIdentityAccessRule provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) DeleteManagedIdentityAccessRule(ctx context.Context, in *gen.DeleteManagedIdentityAccessRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManagedIdentityAccessRule")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteManagedIdentityAccessRuleRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteManagedIdentityAccessRuleRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteManagedIdentityAccessRuleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteManagedIdentityAlias provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) DeleteManagedIdentityAlias(ctx context.Context, in *gen.DeleteManagedIdentityAliasRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManagedIdentityAlias")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteManagedIdentityAliasRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteManagedIdentityAliasRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteManagedIdentityAliasRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManagedIdentities provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) GetManagedIdentities(ctx context.Context, in *gen.GetManagedIdentitiesRequest, opts ...grpc.CallOption) (*gen.GetManagedIdentitiesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetManagedIdentities")
	}

	var r0 *gen.GetManagedIdentitiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentitiesRequest, ...grpc.CallOption) (*gen.GetManagedIdentitiesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentitiesRequest, ...grpc.CallOption) *gen.GetManagedIdentitiesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetManagedIdentitiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetManagedIdentitiesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManagedIdentitiesForWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) GetManagedIdentitiesForWorkspace(ctx context.Context, in *gen.GetManagedIdentitiesForWorkspaceRequest, opts ...grpc.CallOption) (*gen.GetManagedIdentitiesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetManagedIdentitiesForWorkspace")
	}

	var r0 *gen.GetManagedIdentitiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentitiesForWorkspaceRequest, ...grpc.CallOption) (*gen.GetManagedIdentitiesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentitiesForWorkspaceRequest, ...grpc.CallOption) *gen.GetManagedIdentitiesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetManagedIdentitiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetManagedIdentitiesForWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManagedIdentityAccessRuleByID provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) GetManagedIdentityAccessRuleByID(ctx context.Context, in *gen.GetManagedIdentityAccessRuleByIDRequest, opts ...grpc.CallOption) (*gen.ManagedIdentityAccessRule, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetManagedIdentityAccessRuleByID")
	}

	var r0 *gen.ManagedIdentityAccessRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentityAccessRuleByIDRequest, ...grpc.CallOption) (*gen.ManagedIdentityAccessRule, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentityAccessRuleByIDRequest, ...grpc.CallOption) *gen.ManagedIdentityAccessRule); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentityAccessRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetManagedIdentityAccessRuleByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManagedIdentityAccessRules provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) GetManagedIdentityAccessRules(ctx context.Context, in *gen.GetManagedIdentityAccessRulesRequest, opts ...grpc.CallOption) (*gen.GetManagedIdentityAccessRulesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetManagedIdentityAccessRules")
	}

	var r0 *gen.GetManagedIdentityAccessRulesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentityAccessRulesRequest, ...grpc.CallOption) (*gen.GetManagedIdentityAccessRulesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentityAccessRulesRequest, ...grpc.CallOption) *gen.GetManagedIdentityAccessRulesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetManagedIdentityAccessRulesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetManagedIdentityAccessRulesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManagedIdentityByID provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) GetManagedIdentityByID(ctx context.Context, in *gen.GetManagedIdentityByIDRequest, opts ...grpc.CallOption) (*gen.ManagedIdentity, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetManagedIdentityByID")
	}

	var r0 *gen.ManagedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentityByIDRequest, ...grpc.CallOption) (*gen.ManagedIdentity, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetManagedIdentityByIDRequest, ...grpc.CallOption) *gen.ManagedIdentity); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetManagedIdentityByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoveManagedIdentity provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) MoveManagedIdentity(ctx context.Context, in *gen.MoveManagedIdentityRequest, opts ...grpc.CallOption) (*gen.ManagedIdentity, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MoveManagedIdentity")
	}

	var r0 *gen.ManagedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.MoveManagedIdentityRequest, ...grpc.CallOption) (*gen.ManagedIdentity, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.MoveManagedIdentityRequest, ...grpc.CallOption) *gen.ManagedIdentity); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.MoveManagedIdentityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveManagedIdentityFromWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) RemoveManagedIdentityFromWorkspace(ctx context.Context, in *gen.RemoveManagedIdentityFromWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RemoveManagedIdentityFromWorkspace")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.RemoveManagedIdentityFromWorkspaceRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.RemoveManagedIdentityFromWorkspaceRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.RemoveManagedIdentityFromWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateManagedIdentity provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) UpdateManagedIdentity(ctx context.Context, in *gen.UpdateManagedIdentityRequest, opts ...grpc.CallOption) (*gen.ManagedIdentity, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateManagedIdentity")
	}

	var r0 *gen.ManagedIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateManagedIdentityRequest, ...grpc.CallOption) (*gen.ManagedIdentity, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateManagedIdentityRequest, ...grpc.CallOption) *gen.ManagedIdentity); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateManagedIdentityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateManagedIdentityAccessRule provides a mock function with given fields: ctx, in, opts
func (_m *ManagedIdentitiesClient) UpdateManagedIdentityAccessRule(ctx context.Context, in *gen.UpdateManagedIdentityAccessRuleRequest, opts ...grpc.CallOption) (*gen.ManagedIdentityAccessRule, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateManagedIdentityAccessRule")
	}

	var r0 *gen.ManagedIdentityAccessRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateManagedIdentityAccessRuleRequest, ...grpc.CallOption) (*gen.ManagedIdentityAccessRule, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateManagedIdentityAccessRuleRequest, ...grpc.CallOption) *gen.ManagedIdentityAccessRule); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ManagedIdentityAccessRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateManagedIdentityAccessRuleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewManagedIdentitiesClient creates a new instance of ManagedIdentitiesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagedIdentitiesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagedIdentitiesClient {
	mock := &ManagedIdentitiesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
