// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// StateVersionsClient is an autogenerated mock type for the StateVersionsClient type
type StateVersionsClient struct {
	mock.Mock
}

// CreateStateVersion provides a mock function with given fields: ctx, in, opts
func (_m *StateVersionsClient) CreateStateVersion(ctx context.Context, in *gen.CreateStateVersionRequest, opts ...grpc.CallOption) (*gen.StateVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateStateVersion")
	}

	var r0 *gen.StateVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateStateVersionRequest, ...grpc.CallOption) (*gen.StateVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateStateVersionRequest, ...grpc.CallOption) *gen.StateVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.StateVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateStateVersionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStateVersionByID provides a mock function with given fields: ctx, in, opts
func (_m *StateVersionsClient) GetStateVersionByID(ctx context.Context, in *gen.GetStateVersionByIDRequest, opts ...grpc.CallOption) (*gen.StateVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStateVersionByID")
	}

	var r0 *gen.StateVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionByIDRequest, ...grpc.CallOption) (*gen.StateVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionByIDRequest, ...grpc.CallOption) *gen.StateVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.StateVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetStateVersionByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStateVersionOutputByID provides a mock function with given fields: ctx, in, opts
func (_m *StateVersionsClient) GetStateVersionOutputByID(ctx context.Context, in *gen.GetStateVersionOutputByIDRequest, opts ...grpc.CallOption) (*gen.StateVersionOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStateVersionOutputByID")
	}

	var r0 *gen.StateVersionOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionOutputByIDRequest, ...grpc.CallOption) (*gen.StateVersionOutput, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionOutputByIDRequest, ...grpc.CallOption) *gen.StateVersionOutput); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.StateVersionOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetStateVersionOutputByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStateVersionOutputs provides a mock function with given fields: ctx, in, opts
func (_m *StateVersionsClient) GetStateVersionOutputs(ctx context.Context, in *gen.GetStateVersionOutputsRequest, opts ...grpc.CallOption) (*gen.GetStateVersionOutputsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStateVersionOutputs")
	}

	var r0 *gen.GetStateVersionOutputsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionOutputsRequest, ...grpc.CallOption) (*gen.GetStateVersionOutputsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionOutputsRequest, ...grpc.CallOption) *gen.GetStateVersionOutputsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetStateVersionOutputsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetStateVersionOutputsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStateVersions provides a mock function with given fields: ctx, in, opts
func (_m *StateVersionsClient) GetStateVersions(ctx context.Context, in *gen.GetStateVersionsRequest, opts ...grpc.CallOption) (*gen.GetStateVersionsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStateVersions")
	}

	var r0 *gen.GetStateVersionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionsRequest, ...grpc.CallOption) (*gen.GetStateVersionsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetStateVersionsRequest, ...grpc.CallOption) *gen.GetStateVersionsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetStateVersionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetStateVersionsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStateVersionsClient creates a new instance of StateVersionsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateVersionsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateVersionsClient {
	mock := &StateVersionsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
