// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ConfigurationVersionsClient is an autogenerated mock type for the ConfigurationVersionsClient type
type ConfigurationVersionsClient struct {
	mock.Mock
}

// CreateConfigurationVersion provides a mock function with given fields: ctx, in, opts
func (_m *ConfigurationVersionsClient) CreateConfigurationVersion(ctx context.Context, in *gen.CreateConfigurationVersionRequest, opts ...grpc.CallOption) (*gen.ConfigurationVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateConfigurationVersion")
	}

	var r0 *gen.ConfigurationVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateConfigurationVersionRequest, ...grpc.CallOption) (*gen.ConfigurationVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateConfigurationVersionRequest, ...grpc.CallOption) *gen.ConfigurationVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ConfigurationVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateConfigurationVersionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfigurationVersionByID provides a mock function with given fields: ctx, in, opts
func (_m *ConfigurationVersionsClient) GetConfigurationVersionByID(ctx context.Context, in *gen.GetConfigurationVersionByIDRequest, opts ...grpc.CallOption) (*gen.ConfigurationVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigurationVersionByID")
	}

	var r0 *gen.ConfigurationVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetConfigurationVersionByIDRequest, ...grpc.CallOption) (*gen.ConfigurationVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetConfigurationVersionByIDRequest, ...grpc.CallOption) *gen.ConfigurationVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ConfigurationVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetConfigurationVersionByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConfigurationVersionsClient creates a new instance of ConfigurationVersionsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigurationVersionsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigurationVersionsClient {
	mock := &ConfigurationVersionsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
