// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// NamespaceVariablesClient is an autogenerated mock type for the NamespaceVariablesClient type
type NamespaceVariablesClient struct {
	mock.Mock
}

// CreateNamespaceVariable provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) CreateNamespaceVariable(ctx context.Context, in *gen.CreateNamespaceVariableRequest, opts ...grpc.CallOption) (*gen.NamespaceVariable, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateNamespaceVariable")
	}

	var r0 *gen.NamespaceVariable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateNamespaceVariableRequest, ...grpc.CallOption) (*gen.NamespaceVariable, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateNamespaceVariableRequest, ...grpc.CallOption) *gen.NamespaceVariable); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.NamespaceVariable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateNamespaceVariableRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNamespaceVariable provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) DeleteNamespaceVariable(ctx context.Context, in *gen.DeleteNamespaceVariableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespaceVariable")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteNamespaceVariableRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteNamespaceVariableRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteNamespaceVariableRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNamespaceVariableByID provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) GetNamespaceVariableByID(ctx context.Context, in *gen.GetNamespaceVariableByIDRequest, opts ...grpc.CallOption) (*gen.NamespaceVariable, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceVariableByID")
	}

	var r0 *gen.NamespaceVariable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariableByIDRequest, ...grpc.CallOption) (*gen.NamespaceVariable, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariableByIDRequest, ...grpc.CallOption) *gen.NamespaceVariable); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.NamespaceVariable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetNamespaceVariableByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNamespaceVariableVersionByID provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) GetNamespaceVariableVersionByID(ctx context.Context, in *gen.GetNamespaceVariableVersionByIDRequest, opts ...grpc.CallOption) (*gen.NamespaceVariableVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceVariableVersionByID")
	}

	var r0 *gen.NamespaceVariableVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariableVersionByIDRequest, ...grpc.CallOption) (*gen.NamespaceVariableVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariableVersionByIDRequest, ...grpc.CallOption) *gen.NamespaceVariableVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.NamespaceVariableVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetNamespaceVariableVersionByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNamespaceVariableVersions provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) GetNamespaceVariableVersions(ctx context.Context, in *gen.GetNamespaceVariableVersionsRequest, opts ...grpc.CallOption) (*gen.GetNamespaceVariableVersionsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceVariableVersions")
	}

	var r0 *gen.GetNamespaceVariableVersionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariableVersionsRequest, ...grpc.CallOption) (*gen.GetNamespaceVariableVersionsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariableVersionsRequest, ...grpc.CallOption) *gen.GetNamespaceVariableVersionsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetNamespaceVariableVersionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetNamespaceVariableVersionsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNamespaceVariables provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) GetNamespaceVariables(ctx context.Context, in *gen.GetNamespaceVariablesRequest, opts ...grpc.CallOption) (*gen.GetNamespaceVariablesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceVariables")
	}

	var r0 *gen.GetNamespaceVariablesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariablesRequest, ...grpc.CallOption) (*gen.GetNamespaceVariablesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetNamespaceVariablesRequest, ...grpc.CallOption) *gen.GetNamespaceVariablesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetNamespaceVariablesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetNamespaceVariablesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetNamespaceVariables provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) SetNamespaceVariables(ctx context.Context, in *gen.SetNamespaceVariablesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SetNamespaceVariables")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SetNamespaceVariablesRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SetNamespaceVariablesRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SetNamespaceVariablesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNamespaceVariable provides a mock function with given fields: ctx, in, opts
func (_m *NamespaceVariablesClient) UpdateNamespaceVariable(ctx context.Context, in *gen.UpdateNamespaceVariableRequest, opts ...grpc.CallOption) (*gen.NamespaceVariable, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespaceVariable")
	}

	var r0 *gen.NamespaceVariable
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateNamespaceVariableRequest, ...grpc.CallOption) (*gen.NamespaceVariable, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateNamespaceVariableRequest, ...grpc.CallOption) *gen.NamespaceVariable); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.NamespaceVariable)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateNamespaceVariableRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNamespaceVariablesClient creates a new instance of NamespaceVariablesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNamespaceVariablesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NamespaceVariablesClient {
	mock := &NamespaceVariablesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
