// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// GroupsClient is an autogenerated mock type for the GroupsClient type
type GroupsClient struct {
	mock.Mock
}

// CreateGroup provides a mock function with given fields: ctx, in, opts
func (_m *GroupsClient) CreateGroup(ctx context.Context, in *gen.CreateGroupRequest, opts ...grpc.CallOption) (*gen.Group, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *gen.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateGroupRequest, ...grpc.CallOption) (*gen.Group, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateGroupRequest, ...grpc.CallOption) *gen.Group); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateGroupRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGroup provides a mock function with given fields: ctx, in, opts
func (_m *GroupsClient) DeleteGroup(ctx context.Context, in *gen.DeleteGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteGroupRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteGroupRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteGroupRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupByID provides a mock function with given fields: ctx, in, opts
func (_m *GroupsClient) GetGroupByID(ctx context.Context, in *gen.GetGroupByIDRequest, opts ...grpc.CallOption) (*gen.Group, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByID")
	}

	var r0 *gen.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetGroupByIDRequest, ...grpc.CallOption) (*gen.Group, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetGroupByIDRequest, ...grpc.CallOption) *gen.Group); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetGroupByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroups provides a mock function with given fields: ctx, in, opts
func (_m *GroupsClient) GetGroups(ctx context.Context, in *gen.GetGroupsRequest, opts ...grpc.CallOption) (*gen.GetGroupsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 *gen.GetGroupsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetGroupsRequest, ...grpc.CallOption) (*gen.GetGroupsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetGroupsRequest, ...grpc.CallOption) *gen.GetGroupsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetGroupsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetGroupsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrateGroup provides a mock function with given fields: ctx, in, opts
func (_m *GroupsClient) MigrateGroup(ctx context.Context, in *gen.MigrateGroupRequest, opts ...grpc.CallOption) (*gen.Group, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MigrateGroup")
	}

	var r0 *gen.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.MigrateGroupRequest, ...grpc.CallOption) (*gen.Group, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.MigrateGroupRequest, ...grpc.CallOption) *gen.Group); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.MigrateGroupRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateGroup provides a mock function with given fields: ctx, in, opts
func (_m *GroupsClient) UpdateGroup(ctx context.Context, in *gen.UpdateGroupRequest, opts ...grpc.CallOption) (*gen.Group, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 *gen.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateGroupRequest, ...grpc.CallOption) (*gen.Group, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateGroupRequest, ...grpc.CallOption) *gen.Group); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateGroupRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGroupsClient creates a new instance of GroupsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupsClient {
	mock := &GroupsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
