// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// TerraformProvidersClient is an autogenerated mock type for the TerraformProvidersClient type
type TerraformProvidersClient struct {
	mock.Mock
}

// CreateTerraformProvider provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) CreateTerraformProvider(ctx context.Context, in *gen.CreateTerraformProviderRequest, opts ...grpc.CallOption) (*gen.TerraformProvider, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTerraformProvider")
	}

	var r0 *gen.TerraformProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformProviderRequest, ...grpc.CallOption) (*gen.TerraformProvider, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformProviderRequest, ...grpc.CallOption) *gen.TerraformProvider); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateTerraformProviderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTerraformProviderPlatform provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) CreateTerraformProviderPlatform(ctx context.Context, in *gen.CreateTerraformProviderPlatformRequest, opts ...grpc.CallOption) (*gen.TerraformProviderPlatform, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTerraformProviderPlatform")
	}

	var r0 *gen.TerraformProviderPlatform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformProviderPlatformRequest, ...grpc.CallOption) (*gen.TerraformProviderPlatform, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformProviderPlatformRequest, ...grpc.CallOption) *gen.TerraformProviderPlatform); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformProviderPlatform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateTerraformProviderPlatformRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTerraformProviderVersion provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) CreateTerraformProviderVersion(ctx context.Context, in *gen.CreateTerraformProviderVersionRequest, opts ...grpc.CallOption) (*gen.TerraformProviderVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateTerraformProviderVersion")
	}

	var r0 *gen.TerraformProviderVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformProviderVersionRequest, ...grpc.CallOption) (*gen.TerraformProviderVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateTerraformProviderVersionRequest, ...grpc.CallOption) *gen.TerraformProviderVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformProviderVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateTerraformProviderVersionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTerraformProvider provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) DeleteTerraformProvider(ctx context.Context, in *gen.DeleteTerraformProviderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTerraformProvider")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformProviderRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformProviderRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteTerraformProviderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTerraformProviderPlatform provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) DeleteTerraformProviderPlatform(ctx context.Context, in *gen.DeleteTerraformProviderPlatformRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTerraformProviderPlatform")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformProviderPlatformRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformProviderPlatformRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteTerraformProviderPlatformRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTerraformProviderVersion provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) DeleteTerraformProviderVersion(ctx context.Context, in *gen.DeleteTerraformProviderVersionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTerraformProviderVersion")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformProviderVersionRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteTerraformProviderVersionRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteTerraformProviderVersionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformProviderByID provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) GetTerraformProviderByID(ctx context.Context, in *gen.GetTerraformProviderByIDRequest, opts ...grpc.CallOption) (*gen.TerraformProvider, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformProviderByID")
	}

	var r0 *gen.TerraformProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderByIDRequest, ...grpc.CallOption) (*gen.TerraformProvider, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderByIDRequest, ...grpc.CallOption) *gen.TerraformProvider); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformProviderByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformProviderPlatformByID provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) GetTerraformProviderPlatformByID(ctx context.Context, in *gen.GetTerraformProviderPlatformByIDRequest, opts ...grpc.CallOption) (*gen.TerraformProviderPlatform, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformProviderPlatformByID")
	}

	var r0 *gen.TerraformProviderPlatform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderPlatformByIDRequest, ...grpc.CallOption) (*gen.TerraformProviderPlatform, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderPlatformByIDRequest, ...grpc.CallOption) *gen.TerraformProviderPlatform); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformProviderPlatform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformProviderPlatformByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformProviderPlatforms provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) GetTerraformProviderPlatforms(ctx context.Context, in *gen.GetTerraformProviderPlatformsRequest, opts ...grpc.CallOption) (*gen.GetTerraformProviderPlatformsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformProviderPlatforms")
	}

	var r0 *gen.GetTerraformProviderPlatformsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderPlatformsRequest, ...grpc.CallOption) (*gen.GetTerraformProviderPlatformsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderPlatformsRequest, ...grpc.CallOption) *gen.GetTerraformProviderPlatformsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetTerraformProviderPlatformsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformProviderPlatformsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformProviderVersionByID provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) GetTerraformProviderVersionByID(ctx context.Context, in *gen.GetTerraformProviderVersionByIDRequest, opts ...grpc.CallOption) (*gen.TerraformProviderVersion, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformProviderVersionByID")
	}

	var r0 *gen.TerraformProviderVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderVersionByIDRequest, ...grpc.CallOption) (*gen.TerraformProviderVersion, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderVersionByIDRequest, ...grpc.CallOption) *gen.TerraformProviderVersion); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformProviderVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformProviderVersionByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformProviderVersions provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) GetTerraformProviderVersions(ctx context.Context, in *gen.GetTerraformProviderVersionsRequest, opts ...grpc.CallOption) (*gen.GetTerraformProviderVersionsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformProviderVersions")
	}

	var r0 *gen.GetTerraformProviderVersionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderVersionsRequest, ...grpc.CallOption) (*gen.GetTerraformProviderVersionsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProviderVersionsRequest, ...grpc.CallOption) *gen.GetTerraformProviderVersionsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetTerraformProviderVersionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformProviderVersionsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTerraformProviders provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) GetTerraformProviders(ctx context.Context, in *gen.GetTerraformProvidersRequest, opts ...grpc.CallOption) (*gen.GetTerraformProvidersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformProviders")
	}

	var r0 *gen.GetTerraformProvidersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProvidersRequest, ...grpc.CallOption) (*gen.GetTerraformProvidersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetTerraformProvidersRequest, ...grpc.CallOption) *gen.GetTerraformProvidersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetTerraformProvidersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetTerraformProvidersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTerraformProvider provides a mock function with given fields: ctx, in, opts
func (_m *TerraformProvidersClient) UpdateTerraformProvider(ctx context.Context, in *gen.UpdateTerraformProviderRequest, opts ...grpc.CallOption) (*gen.TerraformProvider, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTerraformProvider")
	}

	var r0 *gen.TerraformProvider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateTerraformProviderRequest, ...grpc.CallOption) (*gen.TerraformProvider, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateTerraformProviderRequest, ...grpc.CallOption) *gen.TerraformProvider); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TerraformProvider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateTerraformProviderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTerraformProvidersClient creates a new instance of TerraformProvidersClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerraformProvidersClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerraformProvidersClient {
	mock := &TerraformProvidersClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
