// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/protos/gen"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// WorkspacesClient is an autogenerated mock type for the WorkspacesClient type
type WorkspacesClient struct {
	mock.Mock
}

// CreateWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) CreateWorkspace(ctx context.Context, in *gen.CreateWorkspaceRequest, opts ...grpc.CallOption) (*gen.Workspace, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkspace")
	}

	var r0 *gen.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateWorkspaceRequest, ...grpc.CallOption) (*gen.Workspace, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateWorkspaceRequest, ...grpc.CallOption) *gen.Workspace); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) DeleteWorkspace(ctx context.Context, in *gen.DeleteWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteWorkspaceRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteWorkspaceRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceByID provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) GetWorkspaceByID(ctx context.Context, in *gen.GetWorkspaceByIDRequest, opts ...grpc.CallOption) (*gen.Workspace, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceByID")
	}

	var r0 *gen.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetWorkspaceByIDRequest, ...grpc.CallOption) (*gen.Workspace, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetWorkspaceByIDRequest, ...grpc.CallOption) *gen.Workspace); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetWorkspaceByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaces provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) GetWorkspaces(ctx context.Context, in *gen.GetWorkspacesRequest, opts ...grpc.CallOption) (*gen.GetWorkspacesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaces")
	}

	var r0 *gen.GetWorkspacesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetWorkspacesRequest, ...grpc.CallOption) (*gen.GetWorkspacesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetWorkspacesRequest, ...grpc.CallOption) *gen.GetWorkspacesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetWorkspacesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetWorkspacesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) LockWorkspace(ctx context.Context, in *gen.LockWorkspaceRequest, opts ...grpc.CallOption) (*gen.Workspace, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LockWorkspace")
	}

	var r0 *gen.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.LockWorkspaceRequest, ...grpc.CallOption) (*gen.Workspace, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.LockWorkspaceRequest, ...grpc.CallOption) *gen.Workspace); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.LockWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MigrateWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) MigrateWorkspace(ctx context.Context, in *gen.MigrateWorkspaceRequest, opts ...grpc.CallOption) (*gen.Workspace, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MigrateWorkspace")
	}

	var r0 *gen.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.MigrateWorkspaceRequest, ...grpc.CallOption) (*gen.Workspace, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.MigrateWorkspaceRequest, ...grpc.CallOption) *gen.Workspace); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.MigrateWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToWorkspaceEvents provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) SubscribeToWorkspaceEvents(ctx context.Context, in *gen.SubscribeToWorkspaceEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[gen.WorkspaceEvent], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToWorkspaceEvents")
	}

	var r0 grpc.ServerStreamingClient[gen.WorkspaceEvent]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToWorkspaceEventsRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[gen.WorkspaceEvent], error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.SubscribeToWorkspaceEventsRequest, ...grpc.CallOption) grpc.ServerStreamingClient[gen.WorkspaceEvent]); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[gen.WorkspaceEvent])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.SubscribeToWorkspaceEventsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnlockWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) UnlockWorkspace(ctx context.Context, in *gen.UnlockWorkspaceRequest, opts ...grpc.CallOption) (*gen.Workspace, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UnlockWorkspace")
	}

	var r0 *gen.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UnlockWorkspaceRequest, ...grpc.CallOption) (*gen.Workspace, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UnlockWorkspaceRequest, ...grpc.CallOption) *gen.Workspace); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UnlockWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWorkspace provides a mock function with given fields: ctx, in, opts
func (_m *WorkspacesClient) UpdateWorkspace(ctx context.Context, in *gen.UpdateWorkspaceRequest, opts ...grpc.CallOption) (*gen.Workspace, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspace")
	}

	var r0 *gen.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateWorkspaceRequest, ...grpc.CallOption) (*gen.Workspace, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateWorkspaceRequest, ...grpc.CallOption) *gen.Workspace); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateWorkspaceRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorkspacesClient creates a new instance of WorkspacesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspacesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspacesClient {
	mock := &WorkspacesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
