// Code generated by mockery v2.53.0. DO NOT EDIT.

package tfe

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRESTClient is an autogenerated mock type for the RESTClient type
type MockRESTClient struct {
	mock.Mock
}

// DownloadConfigurationVersion provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) DownloadConfigurationVersion(ctx context.Context, input *DownloadConfigurationVersionInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DownloadConfigurationVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *DownloadConfigurationVersionInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadConfigurationVersion provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) UploadConfigurationVersion(ctx context.Context, input *UploadConfigurationVersionInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadConfigurationVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UploadConfigurationVersionInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadModuleVersion provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) UploadModuleVersion(ctx context.Context, input *UploadModuleVersionInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadModuleVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UploadModuleVersionInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProviderChecksumSignature provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) UploadProviderChecksumSignature(ctx context.Context, input *UploadProviderChecksumSignatureInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadProviderChecksumSignature")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UploadProviderChecksumSignatureInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProviderChecksums provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) UploadProviderChecksums(ctx context.Context, input *UploadProviderChecksumsInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadProviderChecksums")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UploadProviderChecksumsInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProviderPlatformBinary provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) UploadProviderPlatformBinary(ctx context.Context, input *UploadProviderPlatformBinaryInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadProviderPlatformBinary")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UploadProviderPlatformBinaryInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProviderPlatformPackageToMirror provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) UploadProviderPlatformPackageToMirror(ctx context.Context, input *UploadProviderPlatformPackageToMirrorInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadProviderPlatformPackageToMirror")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UploadProviderPlatformPackageToMirrorInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProviderReadme provides a mock function with given fields: ctx, input
func (_m *MockRESTClient) UploadProviderReadme(ctx context.Context, input *UploadProviderReadmeInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UploadProviderReadme")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *UploadProviderReadmeInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRESTClient creates a new instance of MockRESTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRESTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRESTClient {
	mock := &MockRESTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
