// Code generated by mockery v2.53.0. DO NOT EDIT.

package tharsis

import (
	mock "github.com/stretchr/testify/mock"
	pkg "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-sdk-go/pkg"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// ConfigurationVersions provides a mock function with no fields
func (_m *MockClient) ConfigurationVersions() pkg.ConfigurationVersion {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigurationVersions")
	}

	var r0 pkg.ConfigurationVersion
	if rf, ok := ret.Get(0).(func() pkg.ConfigurationVersion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.ConfigurationVersion)
		}
	}

	return r0
}

// Groups provides a mock function with no fields
func (_m *MockClient) Groups() pkg.Group {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Groups")
	}

	var r0 pkg.Group
	if rf, ok := ret.Get(0).(func() pkg.Group); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.Group)
		}
	}

	return r0
}

// Jobs provides a mock function with no fields
func (_m *MockClient) Jobs() pkg.Job {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Jobs")
	}

	var r0 pkg.Job
	if rf, ok := ret.Get(0).(func() pkg.Job); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.Job)
		}
	}

	return r0
}

// ManagedIdentities provides a mock function with no fields
func (_m *MockClient) ManagedIdentities() pkg.ManagedIdentity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ManagedIdentities")
	}

	var r0 pkg.ManagedIdentity
	if rf, ok := ret.Get(0).(func() pkg.ManagedIdentity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.ManagedIdentity)
		}
	}

	return r0
}

// Me provides a mock function with no fields
func (_m *MockClient) Me() pkg.Me {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 pkg.Me
	if rf, ok := ret.Get(0).(func() pkg.Me); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.Me)
		}
	}

	return r0
}

// Runs provides a mock function with no fields
func (_m *MockClient) Runs() pkg.Run {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Runs")
	}

	var r0 pkg.Run
	if rf, ok := ret.Get(0).(func() pkg.Run); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.Run)
		}
	}

	return r0
}

// StateVersions provides a mock function with no fields
func (_m *MockClient) StateVersions() pkg.StateVersion {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StateVersions")
	}

	var r0 pkg.StateVersion
	if rf, ok := ret.Get(0).(func() pkg.StateVersion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.StateVersion)
		}
	}

	return r0
}

// TerraformModuleVersions provides a mock function with no fields
func (_m *MockClient) TerraformModuleVersions() pkg.TerraformModuleVersion {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TerraformModuleVersions")
	}

	var r0 pkg.TerraformModuleVersion
	if rf, ok := ret.Get(0).(func() pkg.TerraformModuleVersion); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.TerraformModuleVersion)
		}
	}

	return r0
}

// TerraformModules provides a mock function with no fields
func (_m *MockClient) TerraformModules() pkg.TerraformModule {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TerraformModules")
	}

	var r0 pkg.TerraformModule
	if rf, ok := ret.Get(0).(func() pkg.TerraformModule); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.TerraformModule)
		}
	}

	return r0
}

// TerraformProviderPlatforms provides a mock function with no fields
func (_m *MockClient) TerraformProviderPlatforms() pkg.TerraformProviderPlatform {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TerraformProviderPlatforms")
	}

	var r0 pkg.TerraformProviderPlatform
	if rf, ok := ret.Get(0).(func() pkg.TerraformProviderPlatform); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.TerraformProviderPlatform)
		}
	}

	return r0
}

// TerraformProviders provides a mock function with no fields
func (_m *MockClient) TerraformProviders() pkg.TerraformProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TerraformProviders")
	}

	var r0 pkg.TerraformProvider
	if rf, ok := ret.Get(0).(func() pkg.TerraformProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.TerraformProvider)
		}
	}

	return r0
}

// Variables provides a mock function with no fields
func (_m *MockClient) Variables() pkg.Variable {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Variables")
	}

	var r0 pkg.Variable
	if rf, ok := ret.Get(0).(func() pkg.Variable); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.Variable)
		}
	}

	return r0
}

// Workspaces provides a mock function with no fields
func (_m *MockClient) Workspaces() pkg.Workspaces {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workspaces")
	}

	var r0 pkg.Workspaces
	if rf, ok := ret.Get(0).(func() pkg.Workspaces); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pkg.Workspaces)
		}
	}

	return r0
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
