package main

import (
	"github.com/mitchellh/cli"
	"gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-cli/internal/command"
	"gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-cli/internal/flag"
)

// commands returns all the available commands.
func commands(baseCommand *command.BaseCommand, globalFlags *flag.Set) (map[string]cli.CommandFactory, error) {
	// The map of all commands except documentation.
	commandMap := map[string]command.Factory{
		"apply":                                    command.NewApplyCommandFactory(baseCommand),
		"caller-identity":                          command.NewCallerIdentityCommandFactory(baseCommand),
		"configure":                                command.NewConfigureCommandFactory(baseCommand),
		"configure delete":                         command.NewConfigureDeleteCommandFactory(baseCommand),
		"configure list":                           command.NewConfigureListCommandFactory(baseCommand),
		"destroy":                                  command.NewDestroyCommandFactory(baseCommand),
		"group":                                    command.NewHelpCommandFactory(getHelpText("group")),
		"group get":                                command.NewGroupGetCommandFactory(baseCommand),
		"group create":                             command.NewGroupCreateCommandFactory(baseCommand),
		"group update":                             command.NewGroupUpdateCommandFactory(baseCommand),
		"group delete":                             command.NewGroupDeleteCommandFactory(baseCommand),
		"group list":                               command.NewGroupListCommandFactory(baseCommand),
		"group migrate":                            command.NewGroupMigrateCommandFactory(baseCommand),
		"group list-memberships":                   command.NewGroupListMembershipsCommandFactory(baseCommand),
		"group get-membership":                     command.NewGroupGetMembershipCommandFactory(baseCommand),
		"group add-membership":                     command.NewGroupAddMembershipCommandFactory(baseCommand),
		"group update-membership":                  command.NewGroupUpdateMembershipCommandFactory(baseCommand),
		"group remove-membership":                  command.NewGroupRemoveMembershipCommandFactory(baseCommand),
		"group get-terraform-var":                  command.NewGroupGetTerraformVarCommandFactory(baseCommand),
		"group set-terraform-var":                  command.NewGroupSetTerraformVarCommandFactory(baseCommand),
		"group delete-terraform-var":               command.NewGroupDeleteTerraformVarCommandFactory(baseCommand),
		"group list-terraform-vars":                command.NewGroupListTerraformVarsCommandFactory(baseCommand),
		"group set-terraform-vars":                 command.NewGroupSetTerraformVarsCommandFactory(baseCommand),
		"group list-environment-vars":              command.NewGroupListEnvironmentVarsCommandFactory(baseCommand),
		"group set-environment-vars":               command.NewGroupSetEnvironmentVarsCommandFactory(baseCommand),
		"managed-identity":                         command.NewHelpCommandFactory(getHelpText("managed-identity")),
		"managed-identity get":                     command.NewManagedIdentityGetCommandFactory(baseCommand),
		"managed-identity create":                  command.NewManagedIdentityCreateCommandFactory(baseCommand),
		"managed-identity update":                  command.NewManagedIdentityUpdateCommandFactory(baseCommand),
		"managed-identity delete":                  command.NewManagedIdentityDeleteCommandFactory(baseCommand),
		"managed-identity list":                    command.NewManagedIdentityListCommandFactory(baseCommand),
		"managed-identity-access-rule":             command.NewHelpCommandFactory(getHelpText("managed-identity-access-rule")),
		"managed-identity-access-rule get":         command.NewManagedIdentityAccessRuleGetCommandFactory(baseCommand),
		"managed-identity-access-rule list":        command.NewManagedIdentityAccessRuleListCommandFactory(baseCommand),
		"managed-identity-access-rule create":      command.NewManagedIdentityAccessRuleCreateCommandFactory(baseCommand),
		"managed-identity-access-rule update":      command.NewManagedIdentityAccessRuleUpdateCommandFactory(baseCommand),
		"managed-identity-access-rule delete":      command.NewManagedIdentityAccessRuleDeleteCommandFactory(baseCommand),
		"managed-identity-alias":                   command.NewHelpCommandFactory(getHelpText("managed-identity-alias")),
		"managed-identity-alias create":            command.NewManagedIdentityAliasCreateCommandFactory(baseCommand),
		"managed-identity-alias delete":            command.NewManagedIdentityAliasDeleteCommandFactory(baseCommand),
		"membership":                               command.NewHelpCommandFactory(getHelpText("membership")),
		"membership list":                          command.NewMembershipListCommandFactory(baseCommand),
		"mcp":                                      command.NewMCPCommandFactory(baseCommand),
		"module":                                   command.NewHelpCommandFactory(getHelpText("module")),
		"module get":                               command.NewModuleGetCommandFactory(baseCommand),
		"module create":                            command.NewModuleCreateCommandFactory(baseCommand),
		"module update":                            command.NewModuleUpdateCommandFactory(baseCommand),
		"module delete":                            command.NewModuleDeleteCommandFactory(baseCommand),
		"module list":                              command.NewModuleListCommandFactory(baseCommand),
		"module list-versions":                     command.NewModuleListVersionsCommandFactory(baseCommand),
		"module list-attestations":                 command.NewModuleListAttestationsCommandFactory(baseCommand),
		"module create-attestation":                command.NewModuleCreateAttestationCommandFactory(baseCommand),
		"module update-attestation":                command.NewModuleUpdateAttestationCommandFactory(baseCommand),
		"module delete-attestation":                command.NewModuleDeleteAttestationCommandFactory(baseCommand),
		"module get-attestation":                   command.NewModuleGetAttestationCommandFactory(baseCommand),
		"module get-version":                       command.NewModuleGetVersionCommandFactory(baseCommand),
		"module delete-version":                    command.NewModuleDeleteVersionCommandFactory(baseCommand),
		"module upload-version":                    command.NewModuleUploadVersionCommandFactory(baseCommand),
		"plan":                                     command.NewPlanCommandFactory(baseCommand),
		"role":                                     command.NewHelpCommandFactory(getHelpText("role")),
		"role get":                                 command.NewRoleGetCommandFactory(baseCommand),
		"role list":                                command.NewRoleListCommandFactory(baseCommand),
		"role create":                              command.NewRoleCreateCommandFactory(baseCommand),
		"role update":                              command.NewRoleUpdateCommandFactory(baseCommand),
		"role delete":                              command.NewRoleDeleteCommandFactory(baseCommand),
		"role get-available-permissions":           command.NewRoleGetAvailablePermissionsCommandFactory(baseCommand),
		"run":                                      command.NewHelpCommandFactory(getHelpText("run")),
		"run cancel":                               command.NewRunCancelCommandFactory(baseCommand),
		"runner-agent":                             command.NewHelpCommandFactory(getHelpText("runner-agent")),
		"runner-agent get":                         command.NewRunnerAgentGetCommandFactory(baseCommand),
		"runner-agent create":                      command.NewRunnerAgentCreateCommandFactory(baseCommand),
		"runner-agent assign-service-account":      command.NewRunnerAgentAssignServiceAccountCommandFactory(baseCommand),
		"runner-agent unassign-service-account":    command.NewRunnerAgentUnassignServiceAccountCommandFactory(baseCommand),
		"runner-agent update":                      command.NewRunnerAgentUpdateCommandFactory(baseCommand),
		"runner-agent delete":                      command.NewRunnerAgentDeleteCommandFactory(baseCommand),
		"runner-agent list":                        command.NewRunnerAgentListCommandFactory(baseCommand),
		"gpg-key":                                  command.NewHelpCommandFactory(getHelpText("gpg-key")),
		"gpg-key get":                              command.NewGPGKeyGetCommandFactory(baseCommand),
		"gpg-key list":                             command.NewGPGKeyListCommandFactory(baseCommand),
		"gpg-key create":                           command.NewGPGKeyCreateCommandFactory(baseCommand),
		"gpg-key delete":                           command.NewGPGKeyDeleteCommandFactory(baseCommand),
		"resource-limit":                           command.NewHelpCommandFactory(getHelpText("resource-limit")),
		"resource-limit list":                      command.NewResourceLimitListCommandFactory(baseCommand),
		"resource-limit update":                    command.NewResourceLimitUpdateCommandFactory(baseCommand),
		"service-account":                          command.NewHelpCommandFactory(getHelpText("service-account")),
		"service-account get":                      command.NewServiceAccountGetCommandFactory(baseCommand),
		"service-account list":                     command.NewServiceAccountListCommandFactory(baseCommand),
		"service-account create":                   command.NewServiceAccountCreateCommandFactory(baseCommand),
		"service-account update":                   command.NewServiceAccountUpdateCommandFactory(baseCommand),
		"service-account delete":                   command.NewServiceAccountDeleteCommandFactory(baseCommand),
		"service-account create-token":             command.NewServiceAccountCreateTokenCommandFactory(baseCommand),
		"sso":                                      command.NewHelpCommandFactory(getHelpText("sso")),
		"sso login":                                command.NewLoginCommandFactory(baseCommand),
		"state-version":                            command.NewHelpCommandFactory(getHelpText("state-version")),
		"state-version get":                        command.NewStateVersionGetCommandFactory(baseCommand),
		"state-version list":                       command.NewStateVersionListCommandFactory(baseCommand),
		"team":                                     command.NewHelpCommandFactory(getHelpText("team")),
		"team get":                                 command.NewTeamGetCommandFactory(baseCommand),
		"team list":                                command.NewTeamListCommandFactory(baseCommand),
		"team create":                              command.NewTeamCreateCommandFactory(baseCommand),
		"team update":                              command.NewTeamUpdateCommandFactory(baseCommand),
		"team delete":                              command.NewTeamDeleteCommandFactory(baseCommand),
		"team add-member":                          command.NewTeamAddMemberCommandFactory(baseCommand),
		"team get-member":                          command.NewTeamGetMemberCommandFactory(baseCommand),
		"team update-member":                       command.NewTeamUpdateMemberCommandFactory(baseCommand),
		"team remove-member":                       command.NewTeamRemoveMemberCommandFactory(baseCommand),
		"team list-members":                        command.NewTeamListMembersCommandFactory(baseCommand),
		"terraform-provider":                       command.NewHelpCommandFactory(getHelpText("terraform-provider")),
		"terraform-provider create":                command.NewTerraformProviderCreateCommandFactory(baseCommand),
		"terraform-provider upload-version":        command.NewTerraformProviderUploadVersionCommandFactory(baseCommand),
		"terraform-provider get":                   command.NewTerraformProviderGetCommandFactory(baseCommand),
		"terraform-provider list":                  command.NewTerraformProviderListCommandFactory(baseCommand),
		"terraform-provider update":                command.NewTerraformProviderUpdateCommandFactory(baseCommand),
		"terraform-provider delete":                command.NewTerraformProviderDeleteCommandFactory(baseCommand),
		"terraform-provider get-version":           command.NewTerraformProviderGetVersionCommandFactory(baseCommand),
		"terraform-provider list-versions":         command.NewTerraformProviderListVersionsCommandFactory(baseCommand),
		"terraform-provider delete-version":        command.NewTerraformProviderDeleteVersionCommandFactory(baseCommand),
		"terraform-provider get-platform":          command.NewTerraformProviderGetPlatformCommandFactory(baseCommand),
		"terraform-provider list-platforms":        command.NewTerraformProviderListPlatformsCommandFactory(baseCommand),
		"terraform-provider delete-platform":       command.NewTerraformProviderDeletePlatformCommandFactory(baseCommand),
		"terraform-provider-mirror":                command.NewHelpCommandFactory(getHelpText("terraform-provider-mirror")),
		"terraform-provider-mirror get-version":    command.NewTerraformProviderMirrorGetVersionCommandFactory(baseCommand),
		"terraform-provider-mirror list-versions":  command.NewTerraformProviderMirrorListVersionsCommandFactory(baseCommand),
		"terraform-provider-mirror list-platforms": command.NewTerraformProviderMirrorListPlatformsCommandFactory(baseCommand),
		"terraform-provider-mirror sync":           command.NewTerraformProviderMirrorSyncCommandFactory(baseCommand),
		"terraform-provider-mirror get-platform":   command.NewTerraformProviderMirrorGetPlatformCommandFactory(baseCommand),
		"terraform-provider-mirror list-platform-mirrors": command.NewTerraformProviderMirrorListPlatformMirrorsCommandFactory(baseCommand),
		"terraform-provider-mirror delete-version":        command.NewTerraformProviderMirrorDeleteVersionCommandFactory(baseCommand),
		"terraform-provider-mirror delete-platform":       command.NewTerraformProviderMirrorDeletePlatformCommandFactory(baseCommand),
		"tf-exec":                                   command.NewTfExecCommandFactory(baseCommand),
		"user":                                      command.NewHelpCommandFactory(getHelpText("user")),
		"user get":                                  command.NewUserGetCommandFactory(baseCommand),
		"user list":                                 command.NewUserListCommandFactory(baseCommand),
		"user create":                               command.NewUserCreateCommandFactory(baseCommand),
		"user delete":                               command.NewUserDeleteCommandFactory(baseCommand),
		"vcs-provider":                              command.NewHelpCommandFactory(getHelpText("vcs-provider")),
		"vcs-provider get":                          command.NewVCSProviderGetCommandFactory(baseCommand),
		"vcs-provider list":                         command.NewVCSProviderListCommandFactory(baseCommand),
		"vcs-provider create":                       command.NewVCSProviderCreateCommandFactory(baseCommand),
		"vcs-provider update":                       command.NewVCSProviderUpdateCommandFactory(baseCommand),
		"vcs-provider delete":                       command.NewVCSProviderDeleteCommandFactory(baseCommand),
		"vcs-provider reset-oauth-token":            command.NewVCSProviderResetOAuthTokenCommandFactory(baseCommand),
		"vcs-provider create-run":                   command.NewVCSProviderCreateRunCommandFactory(baseCommand),
		"vcs-provider-link":                         command.NewHelpCommandFactory(getHelpText("vcs-provider-link")),
		"vcs-provider-link get":                     command.NewVCSProviderLinkGetCommandFactory(baseCommand),
		"vcs-provider-link create":                  command.NewVCSProviderLinkCreateCommandFactory(baseCommand),
		"vcs-provider-link update":                  command.NewVCSProviderLinkUpdateCommandFactory(baseCommand),
		"vcs-provider-link delete":                  command.NewVCSProviderLinkDeleteCommandFactory(baseCommand),
		"version":                                   command.NewVersionCommandFactory(baseCommand),
		"workspace":                                 command.NewHelpCommandFactory(getHelpText("workspace")),
		"workspace get":                             command.NewWorkspaceGetCommandFactory(baseCommand),
		"workspace create":                          command.NewWorkspaceCreateCommandFactory(baseCommand),
		"workspace update":                          command.NewWorkspaceUpdateCommandFactory(baseCommand),
		"workspace delete":                          command.NewWorkspaceDeleteCommandFactory(baseCommand),
		"workspace list":                            command.NewWorkspaceListCommandFactory(baseCommand),
		"workspace lock":                            command.NewWorkspaceLockCommandFactory(baseCommand),
		"workspace unlock":                          command.NewWorkspaceUnlockCommandFactory(baseCommand),
		"workspace migrate":                         command.NewWorkspaceMigrateCommandFactory(baseCommand),
		"workspace list-memberships":                command.NewWorkspaceListMembershipsCommandFactory(baseCommand),
		"workspace get-membership":                  command.NewWorkspaceGetMembershipCommandFactory(baseCommand),
		"workspace add-membership":                  command.NewWorkspaceAddMembershipCommandFactory(baseCommand),
		"workspace update-membership":               command.NewWorkspaceUpdateMembershipCommandFactory(baseCommand),
		"workspace remove-membership":               command.NewWorkspaceRemoveMembershipCommandFactory(baseCommand),
		"workspace assign-managed-identity":         command.NewWorkspaceAssignManagedIdentityCommandFactory(baseCommand),
		"workspace unassign-managed-identity":       command.NewWorkspaceUnassignManagedIdentityCommandFactory(baseCommand),
		"workspace get-assigned-managed-identities": command.NewWorkspaceGetAssignedManagedIdentitiesCommandFactory(baseCommand),
		"workspace outputs":                         command.NewWorkspaceOutputsCommandFactory(baseCommand),
		"workspace label":                           command.NewWorkspaceLabelCommandFactory(baseCommand),
		"workspace get-terraform-var":               command.NewWorkspaceGetTerraformVarCommandFactory(baseCommand),
		"workspace set-terraform-var":               command.NewWorkspaceSetTerraformVarCommandFactory(baseCommand),
		"workspace delete-terraform-var":            command.NewWorkspaceDeleteTerraformVarCommandFactory(baseCommand),
		"workspace list-terraform-vars":             command.NewWorkspaceListTerraformVarsCommandFactory(baseCommand),
		"workspace set-terraform-vars":              command.NewWorkspaceSetTerraformVarsCommandFactory(baseCommand),
		"workspace list-environment-vars":           command.NewWorkspaceListEnvironmentVarsCommandFactory(baseCommand),
		"workspace set-environment-vars":            command.NewWorkspaceSetEnvironmentVarsCommandFactory(baseCommand),
	}

	// Add the documentation commands.
	commandMap["documentation"] = command.NewHelpCommandFactory(getHelpText("documentation"))
	commandMap["documentation generate"] = command.NewDocumentationGenerateCommandFactory(baseCommand, commandMap, globalFlags)

	// Convert CommandFactory to cli.CommandFactory.
	returnMap := map[string]cli.CommandFactory{}
	for name, helpCommandFactory := range commandMap {
		helpCommand, err := helpCommandFactory()
		if err != nil {
			return nil, err
		}

		returnMap[name] = func() (cli.Command, error) {
			return command.NewWrapper(helpCommand), nil
		}
	}

	return returnMap, nil
}
