// Code generated by mockery v2.53.0. DO NOT EDIT.

package acl

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tharsis "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-cli/internal/mcp/tharsis"
	trn "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-cli/internal/trn"
)

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: ctx, client, identifier, resType
func (_m *MockChecker) Authorize(ctx context.Context, client tharsis.Client, identifier string, resType trn.ResourceType) error {
	ret := _m.Called(ctx, client, identifier, resType)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, tharsis.Client, string, trn.ResourceType) error); ok {
		r0 = rf(ctx, client, identifier, resType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
