// Code generated by mockery v2.53.0. DO NOT EDIT.

package acl

import (
	context "context"

	client "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-api/pkg/client"

	mock "github.com/stretchr/testify/mock"

	trn "gitlab.com/infor-cloud/martian-cloud/tharsis/tharsis-cli/internal/trn"
)

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: ctx, _a1, identifier, resType
func (_m *MockChecker) Authorize(ctx context.Context, _a1 *client.Client, identifier string, resType trn.ResourceType) error {
	ret := _m.Called(ctx, _a1, identifier, resType)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *client.Client, string, trn.ResourceType) error); ok {
		r0 = rf(ctx, _a1, identifier, resType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
